# Reusable Deployment Workflow Template
# 
# This template can be used across multiple services for consistent deployments
# 
# Usage:
# Create a workflow file in your service repository:
#
# name: Deploy My Service
# on:
#   workflow_dispatch:
#     inputs:
#       version:
#         required: true
#       environment:
#         required: true
# jobs:
#   deploy:
#     uses: ./.github/workflows/templates/deploy-template.yml
#     with:
#       service_name: my-service
#       version: ${{ inputs.version }}
#       environment: ${{ inputs.environment }}
#     secrets: inherit

name: Reusable Deploy Template

on:
  workflow_call:
    inputs:
      service_name:
        description: 'Service name'
        required: true
        type: string
      version:
        description: 'Version to deploy'
        required: true
        type: string
      environment:
        description: 'Target environment'
        required: true
        type: string
      namespace:
        description: 'Kubernetes namespace'
        required: false
        type: string
      replicas:
        description: 'Number of replicas'
        required: false
        type: number
        default: 4
      port_run_id:
        description: 'Port action run ID'
        required: false
        type: string
    secrets:
      PORT_CLIENT_ID:
        required: false
      PORT_CLIENT_SECRET:
        required: false
      KUBECONFIG:
        required: false
      DOCKER_REGISTRY:
        required: false
    outputs:
      deployment_status:
        description: 'Deployment status'
        value: ${{ jobs.deploy.outputs.status }}
      deployed_version:
        description: 'Deployed version'
        value: ${{ inputs.version }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    outputs:
      status: ${{ steps.rollout.outputs.status }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3

      - name: Configure Kubernetes
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config || echo "Demo mode - using mock config"

      - name: Deploy
        id: deploy
        run: |
          NAMESPACE="${{ inputs.namespace || inputs.environment }}"
          IMAGE="${{ secrets.DOCKER_REGISTRY || 'company.azurecr.io' }}/${{ inputs.service_name }}:${{ inputs.version }}"
          
          echo "Deploying $IMAGE to $NAMESPACE..."
          # kubectl set image deployment/${{ inputs.service_name }} ${{ inputs.service_name }}=$IMAGE -n $NAMESPACE
          # kubectl scale deployment/${{ inputs.service_name }} --replicas=${{ inputs.replicas }} -n $NAMESPACE
          
          echo "✅ Deployment command executed"

      - name: Wait for rollout
        id: rollout
        run: |
          # kubectl rollout status deployment/${{ inputs.service_name }} -n ${{ inputs.namespace || inputs.environment }}
          echo "status=success" >> $GITHUB_OUTPUT
          echo "✅ Rollout complete"

      - name: Update Port
        if: secrets.PORT_CLIENT_ID != ''
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          operation: UPSERT
          identifier: ${{ inputs.service_name }}
          blueprint: application
          properties: |
            {
              "current_version": "${{ inputs.version }}",
              "last_deployment_date": "${{ github.event.repository.updated_at }}",
              "deployment_status": "deployed"
            }
